#!/bin/sh
echo "starting processes: $1 interactive, $2 numeric, $3 massive I/O"
i=$1
n=$2
m=$3
while `expr $i != 0`
do
./a.out 7 &
i=`expr $i - 1`
done
while `expr $n != 0`
do
./a.out 3 &
n=`expr $n - 1`
done
while `expr $m != 0`
do
./a.out 1 &
m=`expr $m - 1`
done
